server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,text/javascript
  http2:
    enabled: true
  tomcat:
    connection-timeout: 20000
    max-http-form-post-size: 2MB
spring:
  application:
    name: memo
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 3600
logging:
  level:
    root: INFO
    com.example.memo: DEBUG
