<?php
// require_once __DIR__ . '/../includes/session.php';
session_start();
// WebCraft - Minecraft Clone Entry Point
?>
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <title>WebCraft - MEMOSITE</title>
    <link rel="stylesheet" href="style.css">
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@400;600;700&display=swap" rel="stylesheet">
    <!-- Three.js & Utils -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/simplex-noise/2.4.0/simplex-noise.min.js"></script>
    <script src="https://unpkg.com/peerjs@1.5.2/dist/peerjs.min.js"></script>
</head>
<body>

    <!-- Game Canvas -->
    <canvas id="game-canvas"></canvas>

    <!-- HUD -->
    <div id="hud" style="display: none;">
        <div id="crosshair">+</div>
        <div id="scope-overlay">
            <div id="scope-crosshair"></div>
        </div>
        <div id="status-bars">
            <div class="status-bar">
                <span class="status-icon">❤️</span>
                <div class="bar-container"><div id="health-bar" class="bar health"></div></div>
                <span id="health-text" style="margin-left: 5px; font-size: 0.8rem;">20/20</span>
            </div>
            <div class="status-bar">
                <span class="status-icon">🍖</span>
                <div class="bar-container"><div id="hunger-bar" class="bar hunger"></div></div>
                <span id="hunger-text" style="margin-left: 5px; font-size: 0.8rem;">20/20</span>
            </div>
        </div>
        
        <div id="money-display" style="position: absolute; top: 20px; right: 20px; font-size: 1.2rem; color: #ffd700; font-weight: bold; background: rgba(0,0,0,0.5); padding: 5px 10px; border-radius: 5px;">
            💰 <span id="money-val">0</span> G
        </div>

        <div id="hotbar">
            <!-- Slots generated by JS -->
        </div>
        <div id="player-list">
            <h4>オンライン・プレイヤー</h4>
            <ul id="players"></ul>
        </div>
        <div id="room-code-display" style="display: none;">
            ルーム: <strong id="room-code-text">ABCD</strong>
            <button id="copy-room-code" onclick="navigator.clipboard.writeText(document.getElementById('room-code-text').textContent)">📋</button>
        </div>
        
        <div id="coordinates">
            <span>X: <span id="coord-x">0</span></span>
            <span>Y: <span id="coord-y">0</span></span>
            <span>Z: <span id="coord-z">0</span></span>
            <span style="margin-left: 10px; color: #aaa;">FPS: <span id="fps">0</span></span>
        </div>

        <div id="chat">
            <div id="chat-messages"></div>
            <input type="text" id="chat-input" placeholder="/help でコマンド一覧を表示..." style="display: none;">
        </div>

        <!-- Mobile Controls -->
        <div id="mobile-controls" style="display: none;">
            <div id="joystick-zone"><div id="joystick-knob"></div></div>
            <div id="mobile-buttons">
                <button id="btn-jump">Jump</button>
                <button id="btn-place">Place</button>
                <button id="btn-break">Break</button>
            </div>
        </div>
    </div>

    <!-- Loading Screen -->
    <div id="loading-screen">
        <div class="loading-content">
            <h1>WebCraft</h1>
            <div class="loading-bar">
                <div class="loading-progress"></div>
            </div>
            <div id="loading-text">リソースを読み込み中...</div>
            <div id="loading-progress-container">
                <div id="loading-progress-bar"></div>
            </div>
        </div>
    </div>

    <!-- Menu Screen Removed -->

    <!-- Pause Menu -->
    <div id="pause-menu" style="display: none;">
        <div class="pause-content">
            <h2>一時停止</h2>
            <div id="pause-room-code" style="display: none; margin-bottom: 15px; color: var(--primary);">
                ルーム: <span id="pause-room-code-text"></span>
            </div>
            <button id="resume-btn" class="menu-btn primary" onclick="document.getElementById('game-canvas').requestPointerLock()">再開</button>
            <div id="save-control" style="display: none;">
                <button id="save-world-btn" class="menu-btn secondary">ワールドを保存</button>
            </div>
            <button id="quit-btn" class="menu-btn danger">メニューに戻る</button>
             <div id="host-controls" style="display: none; margin-top: 10px;">
                <p style="color: var(--text-muted); font-size: 0.8rem;">ホスト操作有効</p>
            </div>
        </div>
    </div>

    <!-- Death Screen -->
    <div id="death-screen" style="display: none;">
        <div class="death-content">
            <h2>死亡しました</h2>
            <p>スコア: <span id="death-score">0</span></p>
            <button id="respawn-btn" class="menu-btn primary">リスポーン</button>
        </div>
    </div>

    <!-- Shop Screen -->
    <!-- Shop Screen -->
    <div id="shop-screen" style="display: none;">
        <div class="shop-content">
            <h2>🛒 フードショップ</h2>
            <div class="shop-money">所持金: <span id="shop-money-val">0</span> G</div>
            <div class="shop-items">
                <div class="shop-item">
                    <div class="shop-icon">🍎</div>
                    <div class="shop-info">
                        <h3>リンゴ</h3>
                        <p>空腹度 +2</p>
                    </div>
                    <button class="menu-btn" onclick="game.buyFood(50, 2)">50 G</button>
                </div>
                <div class="shop-item">
                    <div class="shop-icon">🍞</div>
                    <div class="shop-info">
                        <h3>パン</h3>
                        <p>空腹度 +5</p>
                    </div>
                    <button class="menu-btn" onclick="game.buyFood(100, 5)">100 G</button>
                </div>
                <div class="shop-item">
                    <div class="shop-icon">🥩</div>
                    <div class="shop-info">
                        <h3>ステーキ</h3>
                        <p>空腹度 +8</p>
                    </div>
                    <button class="menu-btn" onclick="game.buyFood(200, 8)">200 G</button>
                </div>
                <div class="shop-item">
                    <div class="shop-icon">🌭</div>
                    <div class="shop-info">
                        <h3>金のリンゴ</h3>
                        <p>全回復</p>
                    </div>
                    <button class="menu-btn special" onclick="game.buyFood(500, 20)">500 G</button>
                </div>
            </div>
            <button class="menu-btn danger" onclick="game.closeShop()">閉じる</button>
        </div>
    </div>

    <script src="network.js?v=<?php echo time(); ?>"></script>
    <script src="animals.js?v=<?php echo time(); ?>"></script>
    <script src="game.js?v=<?php echo time(); ?>"></script>
</body>
</html>
